site_name: Bob's web site
site_url: https://BobGerman.github.io/site/
repo_url: https://github.com/BobGerman/BobGerman.github.io
repo_name: BobGerman/BobGerman.github.io
edit_uri: ''                    # Disable edit button
extra_css:
    - assets/style.css
nav: 
- Home: 'index.md'
- Recipes:
  - (Almost) Margit's Cucumber Salad: 'recipes/cucumber-salad.md'
  - Baked Cod with Bread Crumbs: 'recipes/baked-cod-w-bread-crumbs.md'
  - Bob's New England Style Granola: 'recipes/granola.md'
  - Kate's Mushroom Gravy: 'recipes/mushroom-gravy.md'
  - Miso-glazed Eggplant: 'recipes/miso-glazed-eggplant.md'
  - Smoked Trout Spread: 'recipes/smoked-trout-spread.md'
  - Turkey Meatballs: 'recipes/turkey-meatballs.md'
- DnD:
  - Guild of the Golden Dragon: 'dnd/guild-info.md'
theme:
  name: 'material'
  palette: 
  accent: 'black'
#  logo: 'assets/microsoftteams_appcamp-webheader3.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs         # Top nav
    - navigation.tabs.sticky  # Make top nav stay vaisible
    - navigation.sections
    - toc.integrate           # Integrate sections into left nav
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs/includes
  - admonition
  - pymdownx.details
  - attr_list


